/*
	* OOPSBannerApp UC2 - Banner Display Application
	* 
	* This class demonstrates the creation of a visual banner displaying the word "OOPS" using ASCII art comprised of asteriks (*) and spaces.
	* The banner is printed to the console using individual print staements for each line, creating a decorative text effect.
	*
	* <p> The banner is generated by printing predefined string patterns line by line , where each line contributes to forming the letters O, O,
	* P, S in a stylized format. This extends a basic user story by adding presentation to a simple message output.  </p>
	*
	* @author Developer
	* @version 2.0
*/

// Extend the User story 1 to display the message "OOPS"  in a banner format using charecters formed by spaces and asteriks (*) to create a visual 
// effect for each letter in the message. Use print statements for each line instead of a loop.

public class OOPSBannerApp
{
	public static void main(String[] args)
	{
		System.out.println("   ***    " + "   ***    " + "******    " + "    *****");
		System.out.println(" **   **  " + " **   **  " + "**    **  " + " **      ");
		System.out.println("**     ** " + "**     ** " + "**     ** " + "**       ");
		System.out.println("**     ** " + "**     ** " + "**    **  " + " **      ");
		System.out.println("**     ** " + "**     ** " + "******    " + "   ***   ");
		System.out.println("**     ** " + "**     ** " + "**        " + "      ** ");
		System.out.println("**     ** " + "**     ** " + "**        " + "       **");
		System.out.println(" **   **  " + " **   **  " + "**        " + "      ** ");
		System.out.println("   ***    " + "   ***    " + "**        " + "*****    ");
	}
}
